#stage: dev # Stage Name
#awsRegion: us-east-1
#awsRegionShortName: va #two or three letter abbreviation for the region. You can choose your own abbreviation
#rootUserEmailParamStorePath: '/swb/<stage>/rootUser/email'  # Log into your AWS account and store root user email in SSM Param store
#allowedOrigins: ["http://localhost:3000"] # SWB API will allow this domains to make requests.
#cognitoDomain: 'user-test' # Must be globally unique

# Used for local Lambda development; grab them from Cognito console after cdk-deploy completes.
# Once values are entered, re-run cdk-deploy.
#userPoolId: ''
#clientId: ''
#clientSecret: ''

# Auditing
#fieldsToMaskWhenAuditing: ["user", "password", "accessKey", "code", "codeVerifier"]