## Note:
## Please deploy the swb-reference package before running the integration test suite.
## Settings declared here are merged with the main accounts CFN outputs to create integration test config items

# Default Env Config for launching a new environment
envTypeId: 'et-prod-myqzvzgimloe2,pa-yt42jtbetvbpy'
envTypeConfigId: 'etc-910645aa-d968-41c8-bcd0-bf4e6c90469a'
envType: 'sagemakerNotebook'

#Cognito Integ Test Client
rootUserNameParamStorePath: '/swb/privateTestEnv/rootUser/email'
rootPasswordParamStorePath: '/swb/privateTestEnv/rootUser/password'

projectAdmin1UserNameParamStorePath: '/swb/privateTestEnv/pa1/email'
projectAdmin1PasswordParamStorePath: '/swb/privateTestEnv/pa1/password'

projectAdmin2UserNameParamStorePath: '/swb/privateTestEnv/pa2/email'
projectAdmin2PasswordParamStorePath: '/swb/privateTestEnv/pa2/password'

researcher1UserNameParamStorePath: '/swb/privateTestEnv/researcher1/email'
researcher1PasswordParamStorePath: '/swb/privateTestEnv/researcher1/password'

## Default external ID
externalIdPath: '/rsw/privateTestEnv/externalId'

## Default Hosting Account
defaultHostingAccountId: 'acc-fd3b50d0-2714-460f-a401-28811330caa2'

## Hosting account used for Account Creation tests
hostAwsAccountIdParamStorePath: '/swb/privateTestEnv/accountsTest/awsAccountId'
hostingAccountHandlerRoleArnParamStorePath: '/swb/privateTestEnv/accountsTest/hostingAccountHandlerRoleArn'
envMgmtRoleArnParamStorePath: '/swb/privateTestEnv/accountsTest/envMgmtRoleArn'
encryptionKeyArnParamStorePath: '/swb/privateTestEnv/accountsTest/encryptionKeyArn'
## Pre-requisite for running aws-accounts integration test
awsAccountIdParamStorePath: '/swb/privateTestEnv/accountsTest/awsAccountId'
