## Note:
## Please deploy the swb-reference package before running the integration test suite.
## Settings declared here are merged with the main accounts CFN outputs to create integration test config items

# Default Env Config for launching a new environment
envTypeId: 'b8f160e0-8235-48ca-b928-c057d7ccb309'
envTypeConfigId: 'etc-7f7bd246-1d51-47e9-a5bd-a4530dd8e040'
projectId: 'cf3019e3-88d5-4a64-9025-26a177e36f59'
envType: 'sagemakerNotebook'

# Negative Testing
terminatedEnvId: 'env-b44262fb-ed34-47ae-a4a4-d2d9d9c7a5d5' # id of an environment that has already been terminated

#Cognito Integ Test Client
rootUserNameParamStorePath: '/swb/testEnv/rootUser/email'
rootPasswordParamStorePath: '/swb/testEnv/rootUser/password'

## Default Hosting Account
defaultHostingAccountId: 'acc-827e79f0-f007-4b6a-9640-937abbb98e0d'

## Hosting account used for Account Creation tests
hostAwsAccountIdParamStorePath: '/swb/testEnv/accountsTest/awsAccountId'
