## Note:
## Please deploy the swb-reference package before running the integration test suite.
## Settings declared here are merged with the main accounts CFN outputs to create integration test config items

# Default Env Config for launching a new environment
envTypeId: 'et-prod-q5jnmlalb4eya,pa-lszlpvcp7wukg'
envTypeConfigId: 'etc-7f7bd246-1d51-47e9-a5bd-a4530dd8e040'
projectId: 'proj-8b0d7813-bd0c-41f3-80e6-67129a3d7460'
envType: 'sagemakerNotebook'

# Negative Testing
terminatedEnvId: 'env-b44262fb-ed34-47ae-a4a4-d2d9d9c7a5d5' # id of an environment that has already been terminated

#Cognito Integ Test Client
rootUserNameParamStorePath: '/swb/testEnv/rootUser/email'
rootPasswordParamStorePath: '/swb/testEnv/rootUser/password'

projectAdmin1UserNameParamStorePath: '/swb/testEnv/pa1/email'
projectAdmin1PasswordParamStorePath: '/swb/testEnv/pa1/password'

projectAdmin2UserNameParamStorePath: '/swb/testEnv/pa2/email'
projectAdmin2PasswordParamStorePath: '/swb/testEnv/pa2/password'

researcher1UserNameParamStorePath: '/swb/testEnv/researcher1/email'
researcher1PasswordParamStorePath: '/swb/testEnv/researcher1/password'

## Default Hosting Account
defaultHostingAccountId: 'acc-827e79f0-f007-4b6a-9640-937abbb98e0d'

## Hosting account used for Account Creation tests
hostAwsAccountIdParamStorePath: '/swb/testEnv/accountsTest/awsAccountId'
hostingAccountHandlerRoleArnParamStorePath: '/swb/testEnv/accountsTest/hostingAccountHandlerRoleArn'
envMgmtRoleArnParamStorePath: '/swb/testEnv/accountsTest/envMgmtRoleArn'
encryptionKeyArnParamStorePath: '/swb/testEnv/accountsTest/encryptionKeyArn'
