# AdminUser: 'user@example.com' ##IT Admin User
# AdminPassword: '' ##IT Admin Password
# EnvTypes: [ ##Environment Types to test
#     {
#       EnvironmentType: 'Environemnt Type Name 1', ##Environment Type Name to test
#       EnvironmentTypeConfig: 'Environment Type Config Name 1' ##Environment Type Config Name to use when Environment Type is selected
#     },
#     {
#       EnvironmentType: 'Environemnt Type Name 2', ##Environment Type Name to test
#       EnvironmentTypeConfig: 'Environment Type Config Name 2' ##Environment Type Config Name to use when Environment Type is selected
#     }, ## We can keep adding as many Environment Types elements as we need
# ]
# EnvProject: 'Project 1' ##default environment project name to be selected when creating an environment
# EnvStudies: ['study 1', 'study 2'] ##(OPTIONAL) default environment studies to be selected when creating an environment leave as [] if no studies need to be tested
# CleanEnvironments: false ##set true if we want all environments to be terminated before e2e tests start
