name: npm-publish
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:  
  rush-publish:  
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          ref: ${{ steps.set-ref.outputs.ref }}
          fetch-depth: 0

      - name: Base Action
        uses: ./.github/actions/baseAction

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Set git config
        run: |
          git config user.email ${{ secrets.BOT-USER-EMAIL }}
          git config user.name ${{ secrets.BOT-USER }}
          git config commit.gpgsign true
          
      - name: Rush Publish
        run: |
          PUBLISH_CMD="--add-commit-details --apply --npm-auth-token ${{ secrets.NPM_AUTH_TOKEN }} --ignore-git-hooks --include-all --set-access-level public --target-branch main --publish"
          node common/scripts/install-run-rush.js publish $PUBLISH_CMD
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
