name: Verify Changefiles
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - test-develop

jobs:
  run-rush-change-verify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          fetch-depth: 0
      - name: rush-check-verify
        run: |
          node common/scripts/install-run-rush.js change --verify -b test-develop