#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Viperlight-scan
on: ['pull_request']

jobs:
  viperlight-scan:
    name: Viperlight scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run viperlight scan
        run: node common/scripts/install-run-rush.js viperlight-scan

      - name: Print remediation message
        if: failure()
        run: echo "viperlight scan failed, potential vulnerability. Please review the logs"